In [21]:
import numpy as np

class Organism:

    N_GENES = 10
    P_MUTATION = 0.1

    def __init__(self, genome: np.ndarray = None):
        self.genome = genome if genome is not None else np.zeros(self.N_GENES, dtype=bool)

    def replicate_genome(self):
        copied_genome = self.genome.copy()
        mutations = np.random.rand(self.N_GENES) < self.P_MUTATION  # Mutation mask
        copied_genome ^= mutations  # Flip bits where mutations occur
        return copied_genome

    def divide(self):
        # Perform binary fission by replicating the genome and dividing into two organisms
        offsprings = [
            Organism(genome=self.replicate_genome()),
            Organism(genome=self.replicate_genome()),
        ]
        return offsprings

In [22]:
organism = Organism()

In [23]:
organism.genome

array([False, False, False, False, False, False, False, False, False,
       False])

In [24]:
organism.replicate_genome()

array([False, False, False, False, False,  True, False, False,  True,
       False])

In [36]:
np.stack([x.genome for x in organism.divide()])

array([[ True, False,  True, False, False, False, False, False, False,
         True],
       [False, False, False, False, False, False, False, False, False,
        False]])